
development: 
CONSUMER_KEY = Y9w2xtFMsKp1FAqm3VWx1bput
CONSUMER_SECRET = eArDNF8IhOvpAzLMA0yYEqnOdyItJVFbxkRliqNxhItwg6JMya
YOUR_ACCESS_TOKEN = 2852326364-ZqYKrlpPehcK7QuiygMIfkWg4b9G7j1lqcwAoUE
YOUR_ACCESS_SECRET = EIIiEFKGUm8xEmSDGLnsCtwQSVYehXUTPauqsRkJEVFk7
